 CREATE TABLE "HR"."BVOTE" 
   (	"VTITLE" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"VAUTHOR" VARCHAR2(250 BYTE), 
	"VPUBLISHER" VARCHAR2(250 BYTE) , 
	"VLIKE" NUMBER,
	"VISBN" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE OR REPLACE TRIGGER "HR"."BVOTE_TRG" 
BEFORE INSERT ON BVOTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."BVOTE_TRG" ENABLE;